# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IR-ca_3eN5T_ltKmLHR4NWeMPiBsfObL
"""

vogais = ['a', 'e', 'i', 'o', 'u']

for vogal in vogais:
  print (f"Posição = {vogais.index(vogal)}, valor = {vogal}")