# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1THAYuYwIshRys6AAtPK3qksWh_4uLKhc
"""

linguagens = ["Python", "Java", "Javascript", "c", "C#", "C++","GO","Kotlin"]

print("Antes da listcomp = ", linguagens)

linguagens = [item.lower() for item in linguagens]

print ("\n Depois da Listcomp =", linguagens )