# -*- coding: utf-8 -*-
"""0004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1np51nXtYDGckEy1jaODWaLU-4x4TfiSu
"""

print("Exemplo")
linguagens = '''Python Java Javascript C C# Swift Go Kotlin'''.split()
nova_lista = map(lambda x: x.lower(), linguagens)
print(f"A nova lista é = {nova_lista}\n")
nova_lista = list(nova_lista)
print(f"Agora sim, a nova lista é = {nova_lista}")