# -*- coding: utf-8 -*-
"""0006.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y5wgMH382o5n_vLxQd2uA7Tufg8iudYs
"""

#tuplas
vogais = ('a','e','i','o','u')
print (f"Tipo do objeto vogais = {type(vogais)}")
for p, x in enumerate(vogais):
  print(f"Posição = {p}, valor = {x}")