# -*- coding: utf-8 -*-
"""0008.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Re0NTaXkgR1ZMW86475sHN_npB9BPV5L
"""

a = 2
b = 0.5
c = 1
x = input("Digite o valor de x: ")

x = float(x) # aqui fazemos a conversão da string para o tipo numérico

y = a * x ** 2 + b * x + c

print(f"O resultado de y para x = {x} é {y}.")