# -*- coding: utf-8 -*-
"""0009.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OltMqj3tb8ojeg_gYQxEM6gZ2hjUNNGS
"""

x = 10
nome = 'aluno'
nota = 8.75
fez_inscricao = True

print(type(x))
print(type(nome))
print(type(nota))
print(type(fez_inscricao))