# -*- coding: utf-8 -*-
"""0013.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wlg-Tx2p3c4sMxne9M3gdj5wMHbiFYLY
"""

nomes = 'João Marcela Sonia Daryl Vernon Eder Mechelle Edan Igor Ethan Reed Travis Hoyt'.split()
print('Marcela' in nomes)
print('Roberto' in nomes)