# -*- coding: utf-8 -*-
"""0014.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-vMGhy20KlgVbIcSogQpBwb-yay9qoiE
"""

def executar_busca_linear(lista, valor):
  for elemento in lista:
    if valor == elemento:
      return True
  return False

import random

lista = random.sample(range(100), 20)
print(sorted(lista))
executar_busca_linear(lista, 10)