# -*- coding: utf-8 -*-
"""0015.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NpTjgTJTs1yxti0zEHMbyYopXSautV7l
"""

vogais = "aeiou"
resultado = vogais.index('e')
print(resultado)