# -*- coding: utf-8 -*-
"""0018.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xb7zpA5LLYq1Adap_PGR1Q1_hyNcLsjf
"""

lista = [7, 4]
if lista[0] > lista[1]:
  aux = lista[1]
  lista[1] = lista[0]
  lista[0] = aux
print(lista)