# -*- coding: utf-8 -*-
"""0019.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1arHb83ENWVfmhNBUMWvc8202j2exUROZ
"""

lista = [5, -1]
if lista[0] > lista[1]:
  lista[0], lista[1] = lista[1], lista[0]
print(lista)