# -*- coding: utf-8 -*-
"""0020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dt24k4AYMy5BLFRWEg1W0zXcmnMcuhoh
"""

def executar_selection_sort(lista):
    n = len(lista)
    for i in range(0, n):
        index_menor = i
        for j in range(i+1, n):
            if lista[j] < lista[index_menor]:
             index_menor = j
        lista[i], lista[index_menor] = lista[index_menor], lista[i]
    return lista
lista = [10, 9, 5, 8, 11, -1, 3]
executar_selection_sort(lista)