# -*- coding: utf-8 -*-
"""0022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jcwnxiOzBBgoZLSav0AraoRXK9ELSyll
"""

def executar_insertion_sort(lista):
  n = len(lista)
  for i in range(1, n):
    valor_inserir = lista[i]
    j = i - 1