# -*- coding: utf-8 -*-
"""0024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mlt0R4lbNYY1qCMbRO3Ru9h95PtKfsqC
"""

def executar_quicksort(lista, inicio, fim):
  if inicio < fim:
    pivo = executar_particao(lista, inicio, fim)
    executar_quicksort(lista, inicio, pivo-1)
    executar_quicksort(lista, pivo+1, fim)
  return lista